apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::700913773425:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WEFONYBN3QBP
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::700913773425:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-01T07:25:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "955"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f2f1a196-73e9-11ea-92f2-06ebf8c81af0
